### ISSUE TITLE
Error: secretOrPrivateKey must have a value

### ISSUE THREAD

**Issue by afiz** [cyberflohr/node-red-contrib-google-iot-core#1]
Just need help, due to error mentioned above, how should i enter ther private key. There is no GUI inut box for this

**Comment by cyberflohr** [comment]
You can enter the private key in the TLS configuration dialog (Button below the MQTT server:port input fields)

**Comment by afiz** [comment]
You know what, i'm actually familiar with a normal 'mqtt' node that i used for connecting to AWS IOT, where i used the TLS config mostly. Didn't think that for your 'IOT-Core' node, i can re-use the TLS setting, due to my understanding that Google IOT Core used JWT, so i expect the config is somewhat difference.

But it works! In fact i re-used the cert/key from AWS IOT and it can work with IOT Core (but CA cert must be blank).

Thanks again!
